spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/applepie1130/config-file.git
          timeout: 10
          username: applepie1130
          password: Tjdwnsdk33!
          force-pull: true
          skip-ssl-validation: true
          refresh-rate: 0
          delete-untracked-branches: true
          repos:
            open-mart-api:
              uri: https://github.com/applepie1130/open-mart-config-file.git
              timeout: 10
              username: ${spring.cloud.config.server.git.username}
              password: ${spring.cloud.config.server.git.password}
              pattern: open-mart-api/*
              skip-ssl-validation: true
              force-pull: true
              refresh-rate: 0
              delete-untracked-branches: true